### ISSUE TITLE
Why all the documents are garbled?

### ISSUE THREAD

**Issue by sorrowmaster** [robertpitt/plus-scraper#2]
Is that a coding problem?
I tried to save as ANSI or UTF-8 or Unicode ,but it didn't work.
I'm a noob.. plz tell me what to do, thx~~

**Comment by robertpitt** [comment]
This is now resolved, it was due to Google changing the packages to be gzipped.

patch available here: https://github.com/robertpitt/plus-scraper/commit/7f811f42ed9650114324b233baaa98921d14234b
